export const ADD_BORROWER_STARTED = "ADD_BORROWER_STARTED";
export const ADD_BORROWER_SUCCESS = "ADD_BORROWER_SUCCESS";
export const ADD_BORROWER_ERROR = "ADD_BORROWER_ERROR";
export const SHOW_SUCCESS_MESSAGE_ONCE = "SHOW_SUCCESS_MESSAGE_ONCE";
